language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yursov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yursov/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-962795369625"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"