language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yursov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yursov/docker-react npm run test -- --coverage