version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # means: do not try to map this folder outsied the container
      - .:/app
  tests: # testing service
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # means: do not try to map this folder outsied the container
      - .:/app
    command: ['npm', 'run', 'test']